// Languages offered by the Control center's "Seite übersetzen" and the
// empty-page context menu's "Auf Englisch übersetzen" (which just hardcodes
// "en" from this same list). Codes match Google Translate's `tl` query
// parameter — see electron/main.ts's "translatePage" case in
// controlCenter:action, the proxy-URL approach chosen over a real
// translation API (no key, no running cost, works immediately).
//
// Single source of truth, imported from both the renderer (language picker
// UI) and, indirectly, main.ts (which only needs the code the picker sent
// back) — same reasoning as ZOOM_LEVELS.
export type TranslateLanguage = { code: string; name: string };

export const TRANSLATE_LANGUAGES: TranslateLanguage[] = [
  { code: "en", name: "Englisch" },
  { code: "de", name: "Deutsch" },
  { code: "fr", name: "Französisch" },
  { code: "es", name: "Spanisch" },
  { code: "it", name: "Italienisch" },
  { code: "pt", name: "Portugiesisch" },
  { code: "nl", name: "Niederländisch" },
  { code: "pl", name: "Polnisch" },
  { code: "ru", name: "Russisch" },
  { code: "uk", name: "Ukrainisch" },
  { code: "tr", name: "Türkisch" },
  { code: "el", name: "Griechisch" },
  { code: "sv", name: "Schwedisch" },
  { code: "no", name: "Norwegisch" },
  { code: "da", name: "Dänisch" },
  { code: "fi", name: "Finnisch" },
  { code: "cs", name: "Tschechisch" },
  { code: "sk", name: "Slowakisch" },
  { code: "hu", name: "Ungarisch" },
  { code: "ro", name: "Rumänisch" },
  { code: "bg", name: "Bulgarisch" },
  { code: "hr", name: "Kroatisch" },
  { code: "sr", name: "Serbisch" },
  { code: "sl", name: "Slowenisch" },
  { code: "et", name: "Estnisch" },
  { code: "lv", name: "Lettisch" },
  { code: "lt", name: "Litauisch" },
  { code: "is", name: "Isländisch" },
  { code: "ga", name: "Irisch" },
  { code: "sq", name: "Albanisch" },
  { code: "mk", name: "Mazedonisch" },
  { code: "ar", name: "Arabisch" },
  { code: "he", name: "Hebräisch" },
  { code: "fa", name: "Persisch" },
  { code: "ur", name: "Urdu" },
  { code: "hi", name: "Hindi" },
  { code: "bn", name: "Bengalisch" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
  { code: "gu", name: "Gujarati" },
  { code: "pa", name: "Punjabi" },
  { code: "th", name: "Thai" },
  { code: "vi", name: "Vietnamesisch" },
  { code: "id", name: "Indonesisch" },
  { code: "ms", name: "Malaiisch" },
  { code: "tl", name: "Filipino" },
  { code: "zh-CN", name: "Chinesisch (vereinfacht)" },
  { code: "zh-TW", name: "Chinesisch (traditionell)" },
  { code: "ja", name: "Japanisch" },
  { code: "ko", name: "Koreanisch" },
  { code: "sw", name: "Swahili" },
  { code: "af", name: "Afrikaans" },
  { code: "am", name: "Amharisch" },
  { code: "az", name: "Aserbaidschanisch" },
  { code: "be", name: "Belarussisch" },
  { code: "bs", name: "Bosnisch" },
  { code: "ca", name: "Katalanisch" },
  { code: "cy", name: "Walisisch" },
  { code: "eo", name: "Esperanto" },
  { code: "eu", name: "Baskisch" },
  { code: "gl", name: "Galicisch" },
  { code: "ka", name: "Georgisch" },
  { code: "kk", name: "Kasachisch" },
  { code: "km", name: "Khmer" },
  { code: "ky", name: "Kirgisisch" },
  { code: "lo", name: "Laotisch" },
  { code: "mn", name: "Mongolisch" },
  { code: "ne", name: "Nepalesisch" },
  { code: "si", name: "Singhalesisch" },
  { code: "uz", name: "Usbekisch" },
  { code: "xh", name: "Xhosa" },
  { code: "zu", name: "Zulu" },
];
